kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: build-robot
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch"]