apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: sso
  name: sso
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sso
    spec:
      containers:
      - args:
        env:
        - name: DB_ADDR
          value: "10.11.251.178"
        - name: DB_PORT
          value: "9432"
        - name: DB_DATABASE
          value: keycloak
        - name: DB_PASSWORD
          value: password
        - name: DB_SCHEMA
          value: public
        - name: DB_USER
          value: keycloak
        - name: DB_VENDOR
          value: POSTGRES
        - name: KEYCLOAK_PASSWORD
          value: admin
        - name: KEYCLOAK_USER
          value: admin
        image: jboss/keycloak
        name: sso
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /opt/jboss/keycloak/realm-users.json
          name: sso-claim0
      restartPolicy: Always
      volumes:
      - name: sso-claim0
        persistentVolumeClaim:
          claimName: sso-claim0
status: {}
